### ISSUE TITLE
Lesson: control flow

### ISSUE THREAD

**Issue by tpoisot** [tpoisot/ScientificComputingForTheRestOfUs#12]
This issue is a catch-all for general comments on Lesson 2.

Lesson 2 can be viewed online here: https://nbviewer.jupyter.org/github/tpoisot/ScientificComputingForTheRestOfUs/blob/master/lessons/02_flow_of_execution.ipynb

**Comment by philippbayer** [comment]
This looks extremely polished! I only have one comment - when I started out learning for loops the teacher went through the for loop and wrote down what the placeholder variable `random_number` is for each step, essentially to deconstruct the loop. I think that's a more detailed way of explaining how for loops work.

I've also seen it the other way around - first write out the five (or so) steps the for loop *would* do manually, like

    random_number = random_numbers[0]
    if random_number <= 0.5:
        println('foor')
    else:
        println('bar')
    random_number = random_numbers[1]
    etc.

then show how a for loop can make life easier.
