### ISSUE TITLE
What's the intended audience?

### ISSUE THREAD

**Issue by khinsen** [tpoisot/ScientificComputingForTheRestOfUs#15]
The introduction (README.md) decribes the goals of this lecture material, but without stating who the intended audience is. The overall impression it leaves is "this is a good starting point for anyone doing scientific computing, except for those who need high-performance computing". However, it is probably unrealistic for any concrete down-to-earth material to address the needs of such a wide audience. Notebooks, for example, are great for some scientific applications but a bad match for others. More generally, any tool might be inappropriate simply because many people are constrained in their software choice by the habits of their field. Readers should know from the start that the material might not be right for them, and that it's not their fault (or stupidity) if things don't work out for them.

**Comment by tpoisot** [comment]
Hi @khinsen -- these are good points.

I think the intended audience is "anyone with some experience in using a programming language wanting to get more involved in computing".

Notebooks are just the support for the material, and not the only way to do computing, of course. But I suspect that they will be sufficient for 90% of users.

If you have some suggestions about how to reword, do you want to open a pull request?

**Comment by tpoisot** [comment]
Closed by #16
