### ISSUE TITLE
Logo?

### ISSUE THREAD

**Issue by tpoisot** [tpoisot/ScientificComputingForTheRestOfUs#17]
I would like to have a cool logo for the project, if possible one that would fit on an hex sticker.
I am willing to pay for the design.

**Comment by juanvillada** [comment]
Hi Prof. Poisot!

I think your project is of high value for the rest of us. Please find a very draft I did.

![hex_2logo_scientificcomputingfortherestofus](https://user-images.githubusercontent.com/8431362/33228674-a51d847a-d1fb-11e7-81d8-3d8740168b99.png)

- It has been designed according to the ["Stickers Specification"](https://github.com/terinjokes/StickerConstructorSpec) 

- The only part that is not my original work are the small people vectors, it was [Created by Freepik](https://www.freepik.com/free-photos-vectors/people)

**Comment by philippbayer** [comment]
You can also ask at OpenDesign, we did that for openSNP: https://github.com/mozilla/OpenDesign/issues/63
