### ISSUE TITLE
ML modules

### ISSUE THREAD

**Issue by tpoisot** [tpoisot/ScientificComputingForTheRestOfUs#26]
Pinging @francisbanville @gabrieldansereau  and @graciellehigino (also @aammd)

I've added a `content/machinelearning` folder to store the material for the DataTrek modules - let's brainstorm in the comments, and I'll add a list to this issue

| module | write | review | packages | data source |
|-----|-----|----|-----|----|
| NBC | @tpoisot  | | `Distributions`| seeds |
| Probabilistic programming | @aammd | | `Turing`| | 
| Data ecosystem | | | `DataFrames`| |
| My first neural network | | | `Flux` ? | seeds |

**Comment by tpoisot** [comment]
More broadly, it would be cool to have someone re-read through each lesson leading up to the workshop

**Comment by FrancisBanville** [comment]
It might be interesting to present a module on basic math in Julia (packages `Linear Algebra`, `ODE`, `Calculus`, etc.). I would also like to present a module on genetic algorithms (package `GeneticAlgorithms`), but everything seems exciting to me!

**Comment by tpoisot** [comment]
I like the idea of writing some things from scratch because it's an interesting exercise, but maybe small vignettes about packages are useful too. They require a lot more maintenance work, as APIs can change.

**Comment by graciellehigino** [comment]
Can I call dibs on Data Ecosystem module? Should it be build on the "Map, Filter, Reduce" lesson or can I start a step-by-step guide for DataFrame pkg? I'M TOO EXCITED FOR THAT.

**Comment by tpoisot** [comment]
@graciellehigino sure - this is a good idea, you can either start something new or take over the map filter reduce module
