### ISSUE TITLE
General: intro to notebooks

### ISSUE THREAD

**Issue by tpoisot** [tpoisot/ScientificComputingForTheRestOfUs#6]
This issue is a catch-all for general comments on Lesson 1. 

Lesson 1 can be viewed online here: https://nbviewer.jupyter.org/github/tpoisot/IntroScientificComputing/blob/master/lessons/01_introduction_to_notebooks.ipynb

**Comment by philippbayer** [comment]
Hi Tim, that looks great! Some questions:

- would it make sense to talk about users being able to switch cells from Code to Markdown/Raw etc.? In my courses students often accidentally hit the hotkeys for that and then get confused when their code doesn't execute
- would it make sense to talk about the order of cell execution being important?  Again, something I've seen people struggle with, it's not linear
- I think you need a simile/explanation for the word *variable* (then again, that's part of intro to programming, not intro to notebooks)
- I'd mention keyboard shortcuts exist and that the *h* key lists them all (again, people trigger those accidentally all the time), in my course we start off using the Play button to execute cells and at some point we switch over to Shift+Enter

Again, great work so far! Happy to see this is progressing 🎆

**Comment by tpoisot** [comment]
Hi @dasaderi @trallard & @ha0ye -- if you have a few minutes to spare, I'd love to get your feedback on the first draft of lesson 1.

**Comment by ha0ye** [comment]
Some thoughts:
* how do you expect the lessons to be used (self-run tutorial and/or with an instructor to answer questions)?
* agree with @philippbayer about adding in some UI tips -- double-clicking on a markdown cell enters editing mode, which might be scary
* I think some clear definitions for notebook and programming jargon would benefit users who haven't programmed in a while or are new to notebooks. I myself am confused about *state* - in some uses it seems like there is one state per cell, and in some uses it seems like there is one state per notebook.
* in the cell where you explain why order of execution is important, doing an ```i = 2 * i``` could be a good demonstration of the value changing each time you run just that one cell

**Comment by Balinus** [comment]
Not sure if it's known but there is an error at build time when launching the "binder". Cheers!

**Comment by tpoisot** [comment]
@Balinus yes, this is an issue with Binder -- I am in the process of moving the lessons to webpages to solve this

**Comment by GallowayJ** [comment]
@tpoisot Do you think it would be worthwhile to add a sentence to lesson 0 to clarify that a Jupyter Notebook can run many languages? I've had some beginners who started using Notebooks in with a Python kernel assume that Notebooks could only be used for Python etc. 

"something behind the scenes (called a kernel) took the code, ran it, and then gave you the input." + there are kernels available for most programming languages! [Link to list of available kernels](https://github.com/jupyter/jupyter/wiki/Jupyter-kernels)

Btw I'm happy to make a PR if you think this suggestion is worthwhile.

**Comment by tpoisot** [comment]
Excellent idea, feel free to make a PR!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
